title: ANP Studio
description: Qt 6 desktop application for Analytic Network Process (ANP) modeling
baseurl: "/anp-studio"
url: "https://bamath.org"

markdown: kramdown
theme: minima

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
